import React, { ReactNode } from "react";
import { Inter } from 'next/font/google'
import './globals.css'
import { ContentProvider } from './context/ContentContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface LayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContentProvider>
          {children}
        </ContentProvider>
      </body>
    </html>
  )
}
